### ISSUE TITLE
Laravel 7 and Nova 3 Support

### ISSUE THREAD

**Issue by jnbn** [novius/laravel-nova-order-nestedset-field#6]
Hi Are you going to release something for Laravel 7 and Nova 3 or do you need any help on it?

**Comment by jnbn** [comment]
I saw that it's on dev branch and working properly. I think a merge and tag would be enough =)

**Comment by tonyyb** [comment]
Released in v1.0.0 version !

https://packagist.org/packages/novius/laravel-nova-order-nestedset-field#v1.0.0

Best regards.
