### ISSUE TITLE
Field doesn't show up

### ISSUE THREAD

**Issue by roarkmccolgan** [novius/laravel-nova-order-nestedset-field#7]
Hi! I'm excited for this package thanks very much,
I can't get it to work unfortunately:

I am running a fresh install Laraval 7.12
Laravel Nova 3.6.0
laravel-nova-order-nestedset-field ^1.0

When I follow installation instructions I'm not getting any errors but the index page shows up blank (as expected at first when I have no rows for my nested set model)
![image](https://user-images.githubusercontent.com/1567162/82600801-c6ca8f80-9bae-11ea-9e66-bdac9376330a.png)

But there is no field to add an item on the create page either:
![image](https://user-images.githubusercontent.com/1567162/82600834-d3e77e80-9bae-11ea-986b-a569725807e8.png)

My setup looks like this:
**Model Name**: Section (using both NodeTrait and Orderable traits)
- id
- name
- _lft
- _rgt
- parent_id

I have a Nova resource also called **Section**
with one field - ```OrderNestedsetField::make('Name'),```
and the applyorderings method:
```php
   /**
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param array $orderings
     * @return \Illuminate\Database\Eloquent\Builder
     */
    protected static function applyOrderings($query, array $orderings)
    {
        return $query->orderBy('_lft', 'asc');
    }
```

When I manually create an item:
![image](https://user-images.githubusercontent.com/1567162/82601023-288af980-9baf-11ea-9c10-3013018c7cc5.png)

a row appears on the index page but the **name** field does not show up:
![image](https://user-images.githubusercontent.com/1567162/82601057-3771ac00-9baf-11ea-8ba6-6d491e22c168.png)

Again, there is also no field on the create page of Nova:
![image](https://user-images.githubusercontent.com/1567162/82600834-d3e77e80-9bae-11ea-986b-a569725807e8.png)

Is there something I'm missing?

Thanks!

**Comment by tonyyb** [comment]
Hi, 

Can you share your resource `->fields() ` content please ?

**Comment by roarkmccolgan** [comment]
Hi @tonyyb apologies but I never saw this reply come in. I will try add it again send you the info

Thanks

**Comment by roarkmccolgan** [comment]
Hi @tonyyb 

Turns out it was me not understanding how the package works, although not sure where I went wrong initially as the ordering arrows never showed up the first time I tried.

Now my fields section looks like this:
```php
public function fields(Request $request)
    {
        return [
            Text::make('Name'),
            OrderNestedsetField::make('Order'),
        ];
    }
```
and I get the name and arrows as expected, 
Thanks very much!
